/**
 * Canonical teacher-plan catalog — the single source of truth shared by the
 * dev seed script (`prisma/seed-teacher-plans.ts`) and the self-contained
 * tests. Keeping it here (instead of only in the seed script) means automated
 * tests can upsert the plans themselves and never depend on a manual
 * "run seed first" step.
 */
export interface TeacherPlanSeed {
  code: string;
  name: string;
  displayName: string;
  description: string;
  monthlyPrice: number;
  yearlyPrice: number | null;
  currency: string;
  billingInterval: "MONTHLY";
  isActive: boolean;
  isRecommended: boolean;
  sortOrder: number;
  features: Record<string, boolean>;
  limits: Record<string, number | boolean>;
}

export const TEACHER_PLANS: TeacherPlanSeed[] = [
  {
    code: "FREE",
    name: "free",
    displayName: "الباقة المجانية",
    description: "ابدأ رحلتك التعليمية مع الباقة المجانية — أدوات أساسية للتدريس",
    monthlyPrice: 0,
    yearlyPrice: null,
    currency: "EGP",
    billingInterval: "MONTHLY",
    isActive: true,
    isRecommended: false,
    sortOrder: 0,
    features: {
      aiQuizGeneration: true,
      aiEssayGrading: true,
      unlimitedLessons: true,
      contentProtection: true,
      whatsappSupport: true,
      aiContentGeneration: false,
      aiLessonSummary: false,
      aiQuestionExplanation: false,
      analyticsAccess: false,
      studentEngagementAnalytics: false,
      prioritySupport: false,
      watermark: false,
    },
    limits: {
      aiQuizGenerationsPerMonth: 5,
      aiEssayGradingsPerMonth: 10,
      aiContentGenerationsPerMonth: 0,
      aiLessonSummariesPerMonth: 0,
      aiQuestionExplanationsPerMonth: 0,
      maxStudents: 50,
      maxCourses: 3,
      maxQuizzes: 20,
      storageMb: 500,
      analyticsAccess: false,
      studentEngagementAnalytics: false,
      pdfDownloadTracking: true,
      contentProtection: true,
      prioritySupport: false,
    },
  },
  {
    code: "BASIC",
    name: "basic",
    displayName: "الباقة الأساسية",
    description: "مناسبة للمدرسين الجدد — توليد اختبارات وتصحيح تلقائي",
    monthlyPrice: 199,
    yearlyPrice: 1990,
    currency: "EGP",
    billingInterval: "MONTHLY",
    isActive: true,
    isRecommended: false,
    sortOrder: 1,
    features: {
      aiQuizGeneration: true,
      aiEssayGrading: true,
      aiContentGeneration: true,
      unlimitedLessons: true,
      contentProtection: true,
      analyticsAccess: true,
      whatsappSupport: true,
      aiLessonSummary: false,
      aiQuestionExplanation: false,
      studentEngagementAnalytics: false,
      prioritySupport: false,
      watermark: false,
    },
    limits: {
      aiQuizGenerationsPerMonth: 30,
      aiEssayGradingsPerMonth: 100,
      aiContentGenerationsPerMonth: 10,
      aiLessonSummariesPerMonth: 10,
      aiQuestionExplanationsPerMonth: 10,
      maxStudents: 200,
      maxCourses: 10,
      maxQuizzes: 100,
      storageMb: 5120,
      analyticsAccess: true,
      studentEngagementAnalytics: false,
      pdfDownloadTracking: true,
      contentProtection: true,
      prioritySupport: false,
    },
  },
  {
    code: "PRO",
    name: "pro",
    displayName: "الباقة الاحترافية",
    description: "مناسبة للمدرسين النشطين — كل أدوات الذكاء الاصطناعي والتحليلات",
    monthlyPrice: 499,
    yearlyPrice: 4990,
    currency: "EGP",
    billingInterval: "MONTHLY",
    isActive: true,
    isRecommended: true,
    sortOrder: 2,
    features: {
      aiQuizGeneration: true,
      aiEssayGrading: true,
      aiContentGeneration: true,
      aiLessonSummary: true,
      aiQuestionExplanation: true,
      unlimitedLessons: true,
      contentProtection: true,
      analyticsAccess: true,
      studentEngagementAnalytics: true,
      pdfDownloadTracking: true,
      prioritySupport: true,
      watermark: true,
      whatsappSupport: true,
    },
    limits: {
      aiQuizGenerationsPerMonth: 100,
      aiEssayGradingsPerMonth: 500,
      aiContentGenerationsPerMonth: 50,
      aiLessonSummariesPerMonth: 50,
      aiQuestionExplanationsPerMonth: 50,
      maxStudents: 500,
      maxCourses: 20,
      maxQuizzes: 500,
      storageMb: 10240,
      analyticsAccess: true,
      studentEngagementAnalytics: true,
      pdfDownloadTracking: true,
      contentProtection: true,
      prioritySupport: true,
    },
  },
  {
    code: "PREMIUM",
    name: "premium",
    displayName: "الباقة المميزة",
    description: "للأكاديميات الكبرى — كل الميزات بدون حدود تقريباً",
    monthlyPrice: 999,
    yearlyPrice: 9990,
    currency: "EGP",
    billingInterval: "MONTHLY",
    isActive: true,
    isRecommended: false,
    sortOrder: 3,
    features: {
      aiQuizGeneration: true,
      aiEssayGrading: true,
      aiContentGeneration: true,
      aiLessonSummary: true,
      aiQuestionExplanation: true,
      unlimitedLessons: true,
      contentProtection: true,
      analyticsAccess: true,
      studentEngagementAnalytics: true,
      pdfDownloadTracking: true,
      prioritySupport: true,
      watermark: true,
      whatsappSupport: true,
    },
    limits: {
      aiQuizGenerationsPerMonth: -1,
      aiEssayGradingsPerMonth: -1,
      aiContentGenerationsPerMonth: 200,
      aiLessonSummariesPerMonth: 200,
      aiQuestionExplanationsPerMonth: 200,
      maxStudents: -1,
      maxCourses: 100,
      maxQuizzes: -1,
      storageMb: 51200,
      analyticsAccess: true,
      studentEngagementAnalytics: true,
      pdfDownloadTracking: true,
      contentProtection: true,
      prioritySupport: true,
    },
  },
];
